"use client";import {useEffect,useState} from "react";import Sidebar from "../components/Sidebar";
export default function VideoPage(){const [prompt,setPrompt]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[output,setOutput]=useState(""),[mobileNav,setMobileNav]=useState(false),[usage,setUsage]=useState({today:0,dailyLimit:10}),[balance,setBalance]=useState(0),[billingMode,setBillingMode]=useState("free");
useEffect(()=>{loadAccount()},[]);async function loadAccount(){try{const r=await fetch("/api/account");const d=await r.json();if(r.ok){setUsage(d.usage||{today:0,dailyLimit:10});setBalance(Number(d.balance||0));}}catch{}}
async function generate(){if(!prompt.trim())return setNotice("Enter a prompt first.");if(billingMode==="free"&&usage.today>=usage.dailyLimit)return setNotice("Daily free limit reached. Choose Wallet Balance to continue.");setBusy(true);setNotice("");setOutput("");try{const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"AI Video",prompt,billingMode})});const d=await r.json().catch(()=>({}));if(r.ok&&d.url){setOutput(d.url);setNotice("Video generation completed and saved.");}else setNotice(d.error||"Video generation could not be completed.")}catch{setNotice("Could not reach the generation service.")}finally{setBusy(false)}}
return <main className="shell"><button className="mobileMenu" onClick={()=>setMobileNav(true)}>☰</button>{mobileNav&&<div className="navBackdrop" onClick={()=>setMobileNav(false)}/>}<Sidebar mobileOpen={mobileNav} onNavigate={()=>setMobileNav(false)}/><section className="content"><header><div><label>CREATE · AI VIDEO</label><h1>AI Video Generator</h1><span>Create a short video from a text prompt.</span></div><a className="upgrade" href="/">Dashboard</a></header><div className="workspace"><div className="panel"><label>VIDEO PROMPT</label><h2>Describe your video</h2><textarea maxLength={2000} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="A cinematic drone shot flying over a futuristic city at sunset..."/><div style={{marginTop:16,padding:14,border:"1px solid #ddd",borderRadius:12}}>
<label style={{display:"block",fontWeight:700}}>How do you want to pay?</label>
<div style={{display:"grid",gap:8,marginTop:10}}>
<label><input type="radio" name="videoBilling" checked={billingMode==="free"} onChange={()=>setBillingMode("free")} /> Use Daily Free Limit ({Math.max(0,usage.dailyLimit-usage.today)} remaining)</label>
<label><input type="radio" name="videoBilling" checked={billingMode==="wallet"} onChange={()=>setBillingMode("wallet")} /> Use Wallet Balance (₦{balance.toLocaleString("en-NG",{minimumFractionDigits:2})})</label>
</div></div><div className="foot"><small>{prompt.length}/2000 · {usage.today}/{usage.dailyLimit} free used · Wallet ₦{balance.toLocaleString("en-NG",{minimumFractionDigits:2})}</small><button onClick={generate} disabled={busy||(billingMode==="free"&&usage.today>=usage.dailyLimit)}>{busy?"Generating...":"✦ Generate video"}</button></div>{notice&&<div className="notice">{notice}</div>}</div><div className="panel"><label>OUTPUT</label><h2>Preview</h2><div className="preview">{output?<><video src={output} controls playsInline style={{width:"100%",borderRadius:12}}/><a className="outputLink" href={output} download="ai-video.mp4">Download video</a></>:<><b>✦</b><strong>Your video will appear here</strong><small>Server-side video generation and persistent project media are enabled.</small></>}</div></div></div><footer>AI Media Studio · <a href="/">Dashboard</a></footer></section></main>}