"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import Sidebar from "./components/Sidebar";

const tools=[["AI Image","/image","Generate high-quality images.","IMAGE"],["AI Video","/video","Create short-form video.","VIDEO"],["Scene Generator","/scenes","Build complete visual scenes.","SCENE"],["Storyboard","/storyboard","Plan shots and narrative beats.","STORY"],["AI Editor","/editor","Refine and assemble your media.","EDIT"]];

export default function Home(){
 const [user,setUser]=useState(null),[account,setAccount]=useState(null),[mobileNav,setMobileNav]=useState(false),[showAuth,setShowAuth]=useState(false),[mode,setMode]=useState("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{load();},[]);
 async function load(){try{const me=await fetch("/api/auth/me").then(r=>r.json());setUser(me.user||null);if(me.user){const a=await fetch("/api/account").then(r=>r.json());setAccount(a);}}catch{}}
 async function auth(e){e.preventDefault();setBusy(true);setNotice("");try{const r=await fetch("/api/auth/"+mode,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:email.trim().toLowerCase(),password})});const d=await r.json().catch(()=>({}));if(!r.ok){setNotice(d.error||"Account request failed.");return}setShowAuth(false);setEmail("");setPassword("");await load();}catch{setNotice("Account service did not respond.");}finally{setBusy(false)}}
 function openAuth(m){setMode(m);setNotice("");setShowAuth(true)}
 return <main className="shell"><button className="mobileMenu" onClick={()=>setMobileNav(true)}>☰</button>{mobileNav&&<div className="navBackdrop" onClick={()=>setMobileNav(false)}/>}<Sidebar mobileOpen={mobileNav} onNavigate={()=>setMobileNav(false)}/><section className="content dashboard">
 <header className="dashboardHeader"><div><label>AI MEDIA STUDIO</label><h1>Dashboard</h1><span>Your creative workspace for AI-powered image, video and editing.</span></div>{!user&&<div className="authActions"><button className="upgrade" onClick={()=>openAuth("login")}>Sign in</button><button className="upgrade" onClick={()=>openAuth("register")}>Create account</button></div>}</header>
 <section className="dashboardHero"><div><label>ACCOUNT BALANCE</label><div className="walletBalance">₦{Number(account?.balance||0).toLocaleString("en-NG",{minimumFractionDigits:2})}</div><p>Available funds for AI services</p></div><div className="walletActions"><Link className="primaryAction" href="/settings">Fund account</Link><Link className="secondaryAction" href="/settings">Billing</Link></div></section>
 <section className="overviewGrid"><div className="overviewCard"><span>PLAN</span><strong>{account?"Free":"Guest"}</strong><small>{account?"Starter access":"Sign in to save projects"}</small></div><div className="overviewCard"><span>PROJECTS</span><strong>{account?.usage?.total||0}</strong><small>Saved generations</small></div><div className="overviewCard"><span>DAILY CREDITS</span><strong>{account?.usage?Math.max(0,account.usage.dailyLimit-account.usage.today):10}</strong><small>Free generations remaining</small></div><div className="overviewCard"><span>STATUS</span><strong>Ready</strong><small>Workspace available</small></div></section>
 <section className="dashboardSection"><div className="sectionHeading"><div><label>CREATE</label><h2>Start a new project</h2></div><span>Choose a creative tool.</span></div><div className="toolGrid">{tools.map(([name,href,desc,tag])=><Link className="toolCard" href={href} key={href}><span className="toolIcon">{tag[0]}</span><div className="toolCopy"><strong>{name}</strong><small>{desc}</small></div><b>→</b></Link>)}</div></section>
 <section className="dashboardSection"><div className="sectionHeading"><div><label>WORKSPACE</label><h2>Quick access</h2></div></div><div className="workspaceCards"><Link className="workspaceCard" href="/image"><div><span>CREATE</span><strong>Generate an image</strong><small>Start with a text prompt.</small></div><b>Open →</b></Link><Link className="workspaceCard" href="/editor"><div><span>EDIT</span><strong>Open AI Editor</strong><small>Refine your generated media.</small></div><b>Open →</b></Link><Link className="workspaceCard" href="/settings"><div><span>ACCOUNT</span><strong>Manage billing</strong><small>Funds, account and preferences.</small></div><b>Open →</b></Link></div></section>
 <footer>AI Media Studio · <a href="/api/health">System status</a> · <Link href="/settings">Settings</Link></footer></section>
 {showAuth&&<div className="modal" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setShowAuth(false)}}><form className="auth" onSubmit={auth}><button type="button" className="viewerClose" onClick={()=>!busy&&setShowAuth(false)}>×</button><label>{mode==="login"?"WELCOME BACK":"CREATE ACCOUNT"}</label><h2>{mode==="login"?"Sign in to AI Media Studio":"Create your account"}</h2><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" required/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" minLength={mode==="register"?8:undefined} required/>{notice&&<div className="notice">{notice}</div>}<button className="authBtn" disabled={busy}>{busy?"Please wait...":mode==="login"?"Sign in":"Create account"}</button><button type="button" className="googleButton" onClick={()=>{window.location.href="/api/auth/google"}} disabled={busy}>Continue with Google</button><div className="authSwitch">{mode==="login"?<><span>Don’t have an account?</span><button type="button" onClick={()=>{setMode("register");setNotice("")}}>Create account</button></>:<><span>Already have an account?</span><button type="button" onClick={()=>{setMode("login");setNotice("")}}>Sign in</button></>}</div></form></div>}
 </main>;
}