"use client";
import {useEffect,useState} from "react";
export default function Settings(){
 const [account,setAccount]=useState(null),[amount,setAmount]=useState("5000"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{load();const p=new URLSearchParams(location.search).get("payment");if(p==="success")setMessage("Payment successful. Your wallet balance has been updated.");else if(p==="failed")setMessage("Payment was not completed.");else if(p==="error")setMessage("Payment verification failed. Contact support before trying again.");},[]);
 async function load(){const r=await fetch("/api/account");setAccount(await r.json())}
 async function fund(){setBusy(true);setMessage("");try{const r=await fetch("/api/payments/paystack",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({amount})});const d=await r.json();if(!r.ok){setMessage(d.error||"Could not start payment.");return}location.href=d.authorization_url}catch{setMessage("Payment service did not respond.")}finally{setBusy(false)}}
 async function logout(){const r=await fetch("/api/auth/logout",{method:"POST"});if(r.ok)location.href="/";}
 return <main className="editorShell"><header className="editorHeader"><div><label>ACCOUNT</label><h1>Settings & Billing</h1><span>Manage your profile, wallet and workspace.</span></div><a href="/">Back to Studio</a></header><section className="editorGrid">
 <div className="editorPanel"><label>WALLET</label><h2>₦{Number(account?.balance||0).toLocaleString("en-NG",{minimumFractionDigits:2})}</h2><p>Available account balance for AI services.</p><input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9]/g,""))} inputMode="numeric" placeholder="Amount in NGN"/><button className="primary" onClick={fund} disabled={busy}>{busy?"Opening secure checkout...":"Fund account"}</button>{message&&<p>{message}</p>}<p>Payments are processed securely through Paystack. Your card or bank details are entered on Paystack's checkout, not stored by this application.</p></div>
 <div className="editorPanel"><label>PROFILE</label>{account?.user?<><h2>{account.user.email}</h2><p>Created: {new Date(account.user.created_at).toLocaleString()}</p><button className="primary" onClick={logout}>Sign out</button></>:<p>{account?.error||"Loading account..."}</p>}</div>
 <div className="editorPanel"><label>PLAN & USAGE</label>{account?.usage?<><h2>Free plan</h2><p>{account.usage.today} / {account.usage.dailyLimit} free generations used today.</p><p>{Math.max(0,account.usage.dailyLimit-account.usage.today)} free generations remaining.</p><p>{account.usage.total} total generations saved.</p></>:<p>Loading usage...</p>}</div>
 </section></main>
}